# Nom du projet dans SonarQube
sonar.projectKey=MonProjetSpringBoot
sonar.projectName=MonProjetSpringBoot
sonar.projectVersion=1.0

# URL de SonarQube
sonar.host.url=http://localhost:9000

# Token d'authentification (copié depuis SonarQube)
sonar.login=squ_f43a97d13abd74681fac6278a7d2eaab05640f91

# Sources à analyser
sonar.sources=src/main/java
sonar.tests=src/test/java

# Langage (Java)
sonar.language=java